spring.application.name=api
server.port=${PORT:8080}

# Configuracoes de conexao com o MySQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/ignitionmotors?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuracoes do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Token JWT
api.security.token.secret=${JWT_SECRET:minha-chave-secreta-e-super-segura-do-ignition-motors}
